export const DEFAULT_TERMS_LIST = [
  '1. Payment: All payments must be made via cash, EFTPOS, or cleared bank transfer before or upon pickup. No work will commence without payment confirmation.',
  '2. Claims and Complaints: No claims will be entertained once the driver has left the pickup or delivery address. Any issues must be reported before departure.',
  '3. Fragile Items and Customer-Packed Boxes: Delivery Plus Australia holds no responsibility for fragile or loose items such as glassware, mirrors, or goods packed by the customer.',
  '4. Stairs and Tolls: All toll fees and stair-related access charges are to be paid by the customer unless otherwise stated in the quote.',
  '5. Hard Access Properties: Additional charges may apply for difficult access including long carry distances, steep driveways, or narrow access.',
  '6. Cubic Metre Limit: The customer is allocated the truck space quoted. Additional charges may apply if the load exceeds the quoted volume.',
  '7. TVs, Electronics and Fragile Goods: Please refer to the detailed Terms & Conditions supplied with the booking confirmation for limitations relating to fragile and sensitive goods.',
  '8. Property Access and Damage Waiver: Where stairs or difficult access exist, the applicable damage waiver and access conditions apply.',
];

export const AVAILABLE_VARIABLES = [
  { group: 'Customer', variables: [
    { key: '{{customer_name}}', desc: 'Customer Full Name', sample: 'Shivam Sharma' },
    { key: '{{customer_phone}}', desc: 'Customer Phone Number', sample: '0412 345 678' },
    { key: '{{customer_email}}', desc: 'Customer Email Address', sample: 'shivam@example.com' },
  ]},
  { group: 'Job Details', variables: [
    { key: '{{job_id}}', desc: 'Job / Quote Reference ID', sample: 'JOB-00027' },
    { key: '{{job_type}}', desc: 'Type of Job (Delivery / Moving)', sample: 'Moving' },
    { key: '{{pickup_location}}', desc: 'Pickup Full Address', sample: '123 Collins St, Melbourne VIC 3000' },
    { key: '{{dropoff_location}}', desc: 'Drop-off Full Address', sample: '456 Chapel St, South Yarra VIC 3141' },
    { key: '{{booking_date}}', desc: 'Scheduled Booking Date', sample: '24/08/2026' },
    { key: '{{booking_time}}', desc: 'Scheduled Booking Time', sample: '09:00 AM' },
    { key: '{{truck_size}}', desc: 'Vehicle / Truck Size', sample: '4.5 Tonne' },
    { key: '{{movers_count}}', desc: 'Number of Movers', sample: '2 Movers' },
    { key: '{{property_size}}', desc: 'Property Size / Bedrooms', sample: '2 bedrooms' },
  ]},
  { group: 'Pricing', variables: [
    { key: '{{pricing_type}}', desc: 'Hourly or Fixed pricing', sample: 'Hourly' },
    { key: '{{hourly_rate}}', desc: 'Hourly Rate Amount', sample: '$120.00' },
    { key: '{{fixed_price}}', desc: 'Fixed Price Amount', sample: '$850.00' },
    { key: '{{deposit_amount}}', desc: 'Booking Deposit Amount', sample: '$100.00' },
    { key: '{{minimum_estimated_cost}}', desc: 'Minimum Estimated Total', sample: '$360.00' },
    { key: '{{callout_charge}}', desc: 'Callout Charge Amount', sample: '$60.00' },
    { key: '{{travel_back_charge}}', desc: 'Travel Back Charge Amount', sample: '$60.00' },
    { key: '{{stairs_charge}}', desc: 'Stairs Charge Amount', sample: '$40.00' },
    { key: '{{subtotal}}', desc: 'Subtotal Amount', sample: '$850.00' },
    { key: '{{total_amount}}', desc: 'Total Amount', sample: '$850.00' },
  ]},
  { group: 'Booking & Status', variables: [
    { key: '{{booking_status}}', desc: 'Current Booking Status', sample: 'Confirmed' },
    { key: '{{confirmed_at}}', desc: 'Confirmation Date', sample: '24/08/2026' },
  ]},
  { group: 'Driver & Vehicle', variables: [
    { key: '{{driver_name}}', desc: 'Assigned Driver Name', sample: 'Alex Kumar' },
    { key: '{{driver_phone}}', desc: 'Driver Phone Number', sample: '0498 765 432' },
    { key: '{{vehicle_name}}', desc: 'Vehicle Name / Model', sample: 'Isuzu 4.5T Truck' },
    { key: '{{vehicle_number}}', desc: 'Vehicle Rego Number', sample: '1AB-2CD' },
  ]},
  { group: 'Company Info', variables: [
    { key: '{{company_name}}', desc: 'Company Legal Name', sample: 'Delivery Plus Australia' },
    { key: '{{company_phone}}', desc: 'Company Support Phone', sample: '03 7008 5094' },
    { key: '{{company_mobile}}', desc: 'Company Mobile Phone', sample: '04 2479 6524' },
    { key: '{{company_email}}', desc: 'Company Support Email', sample: 'info@deliveryplus.com.au' },
    { key: '{{company_website}}', desc: 'Company Website URL', sample: 'https://deliveryplus.com.au' },
  ]},
  { group: 'Bank Details', variables: [
    { key: '{{bank_name}}', desc: 'Bank Name', sample: 'Commonwealth Bank of Australia' },
    { key: '{{bank_account_name}}', desc: 'Bank Account Name', sample: 'Delivery Plus Australia' },
    { key: '{{bank_bsb}}', desc: 'BSB Number', sample: '063-000' },
    { key: '{{bank_account_number}}', desc: 'Bank Account Number', sample: '1234 5678' },
    { key: '{{bank_reference}}', desc: 'Payment Reference Code', sample: 'JOB-00027' },
  ]},
];

export const SAMPLE_DATA_MAP = {
  '{{customer_name}}': 'Shivam Sharma',
  '{{CUSTOMER_NAME}}': 'Shivam Sharma',
  '{{customer_phone}}': '0412 345 678',
  '{{CUSTOMER_PHONE}}': '0412 345 678',
  '{{customer_email}}': 'shivam@example.com',
  '{{CUSTOMER_EMAIL}}': 'shivam@example.com',
  '{{job_id}}': 'JOB-00027',
  '{{JOB_ID}}': 'JOB-00027',
  '{{job_number}}': 'JOB-00027',
  '{{JOB_NUMBER}}': 'JOB-00027',
  '{{job_type}}': 'Moving',
  '{{pickup_location}}': '123 Collins St, Melbourne VIC 3000',
  '{{dropoff_location}}': '456 Chapel St, South Yarra VIC 3141',
  '{{booking_date}}': '24/08/2026',
  '{{booking_time}}': '09:00 AM',
  '{{truck_size}}': '4.5 Tonne',
  '{{movers_count}}': '2 Movers',
  '{{property_size}}': '2 bedrooms',
  '{{pricing_type}}': 'Hourly',
  '{{hourly_rate}}': '$120.00',
  '{{fixed_price}}': '$850.00',
  '{{deposit_amount}}': '$100.00',
  '{{minimum_estimated_cost}}': '$360.00',
  '{{callout_charge}}': '$60.00',
  '{{travel_back_charge}}': '$60.00',
  '{{stairs_charge}}': '$40.00',
  '{{subtotal}}': '$850.00',
  '{{total_amount}}': '$850.00',
  '{{booking_status}}': 'Confirmed',
  '{{confirmed_at}}': '24/08/2026',
  '{{driver_name}}': 'Alex Kumar',
  '{{driver_phone}}': '0498 765 432',
  '{{vehicle_name}}': 'Isuzu 4.5T Truck',
  '{{vehicle_number}}': '1AB-2CD',
  '{{company_name}}': 'Delivery Plus Australia',
  '{{company_phone}}': '03 7008 5094',
  '{{company_mobile}}': '04 2479 6524',
  '{{company_email}}': 'info@deliveryplus.com.au',
  '{{company_website}}': 'https://deliveryplus.com.au',
  '{{bank_name}}': 'Commonwealth Bank of Australia',
  '{{bank_account_name}}': 'Delivery Plus Australia',
  '{{bank_bsb}}': '063-000',
  '{{bank_account_number}}': '1234 5678',
  '{{bank_reference}}': 'JOB-00027',
};

export const DEFAULT_QUOTATION_TEMPLATE = {
  templateKey: 'quotation',
  name: 'Quotation Email',
  description: 'Email sent to customer when a quotation is created or sent.',
  subject: 'Delivery Plus Quotation – {{job_id}}',
  isActive: true,
  contentConfig: {
    badgeText: 'Quotation',
    heroCopy: 'Thank you for choosing Delivery Plus. Please review your relocation details and quotation below.',
    greeting: 'Hi {{customer_name}},',
    subGreeting: 'Please review your job details and quotation below.',
    reviewLinkText: '★★★★★ Google Reviews',
    reviewLinkUrl: 'https://www.google.com/maps/place/Delivery+Plus/@-37.6845757,144.9599025,689m/data=!3m2!1e3!4b1!4m6!3m5!1s0x62794944bd5d04d7:0x3d4478c3c50c22d3!8m2!3d-37.6845757!4d144.9599025!16s%2Fg%2F11kc2jc6p0?entry=ttu&g_ep=EgoyMDI2MDkwMS4wIKXMDSoASAFQAw%3D%3D',
    referenceCardTitle: 'Quote Reference',
    jobOverviewTitle: 'Job Overview',
    routeSectionTitle: 'Pickup & Drop-off',
    movingDetailsTitle: 'Moving Details',
    costBreakdownTitle: 'Cost Breakdown',
    depositCardTitle: 'Booking Deposit',
    depositCardHeading: 'Secure your booking',
    depositCardText: 'To confirm your booking, the deposit below is required. This amount will be adjusted against the final payment once the job is completed.',
    bankDetailsTitle: 'Bank Details for Deposit',
    bankDetailsSubtitle: 'Direct Bank Transfer',
    bankName: 'Commonwealth Bank of Australia',
    bankAccountName: 'Delivery Plus Australia',
    bankBsb: '063-000',
    bankAccountNumber: '1234 5678',
    bankReference: '{{job_id}}',
    bankPaymentInstructions: 'Please transfer the deposit amount of {{deposit_amount}} using your Quote Reference ({{job_id}}) as description, and email receipt to info@deliveryplus.com.au.',
    paymentNoticeTitle: 'Important Payment Notice',
    paymentNoticeText: 'Payment must be made when approximately 75% of the truck has been unloaded at the delivery address.',
    notesTitle: 'Notes',
    notesSubtitle: 'Special Instructions',
    termsKicker: 'Please Read',
    termsTitle: 'Terms & Conditions',
    termsList: DEFAULT_TERMS_LIST,
    signoffGreeting: 'Regards,',
    signoffName: 'Anu',
    signoffTeam: 'Team Delivery Plus',
    footerCompanyName: 'Delivery Plus Australia',
    footerTagline: 'Trusted Transit at Affordable Prices',
    footerPhone1: '03 7008 5094',
    footerPhone2: '04 2479 6524',
  },
  designConfig: {
    primaryColor: '#00B9E8',
    secondaryColor: '#101D4F',
    headerBgColor: '#0D1B4C',
    pageBgColor: '#EEF4F8',
    cardBgColor: '#ffffff',
    textColor: '#59677A',
    headingColor: '#101D4F',
    borderColor: '#DDE6EE',
    emailWidth: '700px',
    borderRadius: '16px',
    fontFamily: 'Arial, Helvetica, sans-serif',
  },
  logoConfig: {
    enabled: true,
    useAttachment: true,
    customUrl: '',
    width: 220,
    alignment: 'left',
  },
  ctaConfig: {
    enabled: false,
    text: 'View Quotation',
    url: '',
    bgColor: '#00B9E8',
    textColor: '#ffffff',
    borderRadius: '8px',
    alignment: 'center',
  },
  sectionsConfig: [
    { id: 'header', name: 'Header & Logo', enabled: true, order: 1 },
    { id: 'hero', name: 'Greeting & Review Link', enabled: true, order: 2 },
    { id: 'quoteReference', name: 'Quote Reference Card', enabled: true, order: 3 },
    { id: 'overviewAndRoute', name: 'Job Overview & Pickup / Drop-off', enabled: true, order: 4 },
    { id: 'movingDetails', name: 'Moving Service Details', enabled: true, order: 5 },
    { id: 'costBreakdown', name: 'Cost Breakdown Table', enabled: true, order: 6 },
    { id: 'bookingDeposit', name: 'Booking Deposit Card', enabled: true, order: 7 },
    { id: 'bankDetails', name: 'Bank Details / Payment Card', enabled: true, order: 8 },
    { id: 'paymentNotice', name: 'Payment Notice Banner', enabled: true, order: 9 },
    { id: 'notes', name: 'Special Notes', enabled: true, order: 10 },
    { id: 'cta', name: 'Action Button (CTA)', enabled: false, order: 11 },
    { id: 'terms', name: 'Terms & Conditions', enabled: false, order: 12 },
    { id: 'signoff', name: 'Sign-off Signature', enabled: true, order: 13 },
    { id: 'footer', name: 'Footer & Contact Info', enabled: true, order: 14 },
  ],
};

export const DEFAULT_BOOKING_CONFIRMATION_TEMPLATE = {
  templateKey: 'booking_confirmation',
  name: 'Booking Confirmation',
  description: 'Email sent to customer after a booking deposit is received and confirmed.',
  subject: 'Delivery Plus Booking Confirmation – {{job_id}}',
  isActive: true,
  contentConfig: {
    badgeText: '✓ Booking Confirmation',
    heading: 'Your booking is confirmed',
    heroCopy: 'This email confirms your booking and the deposit received for your move.',
    depositCardBadge: '✓ Deposit Received',
    depositCardStatus: 'Status: Received / Confirmed',
    greeting: 'Hi {{customer_name}},',
    confirmationMessage: 'This email confirms that we received your booking deposit of {{deposit_amount}}. This amount will be adjusted in the total move cost at the time of final payment.',
    serviceDetailsTitle: 'Service Details',
    costBreakdownTitle: 'Cost Breakdown',
    minimumEstimatedCostTitle: 'Minimum Estimated Cost',
    minimumEstimatedCostFootnote: 'Includes the minimum booking period, callout and travel-back charges.',
    journeyTitle: '🚚 Your Journey',
    itemListTitle: 'List of Items',
    termsKicker: 'Please Read',
    termsTitle: 'Terms & Conditions',
    termsList: DEFAULT_TERMS_LIST,
    signoffGreeting: 'Regards,',
    signoffName: 'Team Delivery Plus',
    signoffTeam: 'Delivery Plus Australia',
    footerCompanyName: 'Delivery Plus Australia',
    footerTagline: 'Trusted Transit at Affordable Prices',
    footerPhone1: '03 7008 5094',
    footerPhone2: '04 2479 6524',
  },
  designConfig: {
    primaryColor: '#0F766E',
    secondaryColor: '#0B163D',
    headerBgColor: '#0B163D',
    pageBgColor: '#F1F5F9',
    cardBgColor: '#ffffff',
    textColor: '#58667A',
    headingColor: '#0B163D',
    borderColor: '#E6ECF5',
    emailWidth: '700px',
    borderRadius: '16px',
    fontFamily: 'Arial, Helvetica, sans-serif',
  },
  logoConfig: {
    enabled: true,
    useAttachment: true,
    customUrl: '',
    width: 220,
    alignment: 'left',
  },
  ctaConfig: {
    enabled: false,
    text: 'View Booking Details',
    url: '',
    bgColor: '#0F766E',
    textColor: '#ffffff',
    borderRadius: '8px',
    alignment: 'center',
  },
  sectionsConfig: [
    { id: 'header', name: 'Header & Logo', enabled: true, order: 1 },
    { id: 'hero', name: 'Hero Banner & Heading', enabled: true, order: 2 },
    { id: 'depositConfirmed', name: 'Deposit Received Card', enabled: true, order: 3 },
    { id: 'greeting', name: 'Greeting & Confirmation Text', enabled: true, order: 4 },
    { id: 'serviceDetails', name: 'Service Details Table', enabled: true, order: 5 },
    { id: 'costBreakdown', name: 'Cost Breakdown', enabled: true, order: 6 },
    { id: 'minimumEstimatedCost', name: 'Minimum Estimated Cost Card', enabled: true, order: 7 },
    { id: 'journey', name: 'Your Journey (Route)', enabled: true, order: 8 },
    { id: 'itemList', name: 'List of Items', enabled: true, order: 9 },
    { id: 'cta', name: 'Action Button (CTA)', enabled: false, order: 10 },
    { id: 'terms', name: 'Terms & Conditions', enabled: true, order: 11 },
    { id: 'signoff', name: 'Sign-off Signature', enabled: true, order: 12 },
    { id: 'footer', name: 'Footer & Contact Info', enabled: true, order: 13 },
  ],
};

export const getDefaultTemplateConfig = (templateKey) => {
  if (templateKey === 'quotation') {
    return JSON.parse(JSON.stringify(DEFAULT_QUOTATION_TEMPLATE));
  }
  if (templateKey === 'booking_confirmation') {
    return JSON.parse(JSON.stringify(DEFAULT_BOOKING_CONFIRMATION_TEMPLATE));
  }
  return null;
};
